name: Selenium (Java)

on:
  push:
    paths:
      - "selenium-java/**"
  pull_request:
    paths:
      - "selenium-java/**"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: selenium-java-pages
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run tests in Docker
        run: docker compose up --build --abort-on-container-exit --exit-code-from selenium-java selenium-java

      - name: Stop Docker services
        if: always()
        run: docker compose down -v

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          allure_results: artifacts/selenium-java/allure-results
          allure_report: artifacts/selenium-java/allure-report
          gh_pages: gh-pages
          allure_history: artifacts/selenium-java/allure-history
          subfolder: selenium-java

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: artifacts/selenium-java/allure-history/selenium-java
          destination_dir: selenium-java
